version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  commit-message:
    # dependencies for semantic-release won't affect behavior of the product
    prefix: "build"
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
