language: java
sudo: false
jdk: oraclejdk8
install:
  - nvm install
  - yarn install
script:
  - ./mvnw verify
jobs:
  include:
    - stage: deploy
      script:
        - openssl aes-256-cbc -K $encrypted_1636434a17e8_key -iv $encrypted_1636434a17e8_iv -in .travis/codesigning.asc.enc -out .travis/codesigning.asc -d
        - gpg --fast-import .travis/codesigning.asc
        - travis_wait yarn run semantic-release
